# importing modules
from youtube_transcript_api import YouTubeTranscriptApi

# using the srt variable with the list of dictionaries 
# obtained by the .get_transcript() function
# srt = YouTubeTranscriptApi.get_transcript("EhmQQLzm5b0",languages=['en'])
srt = YouTubeTranscriptApi.get_transcript("Ha6guNv9fOA")
# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts('Ha6guNv9fOA')
# iterate over all available transcripts
for transcript in transcript_list:
 
    # the Transcript object provides metadata
    # properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
       
    #     # whether it has been manually created or
    #     # generated by YouTube
        transcript.is_generated,
         
    #     # whether this transcript can be translated 
    #     # or not
        transcript.is_translatable,
         
    #     # a list of languages the transcript can be 
    #     # translated to
        transcript.translation_languages,
    )
    # fetch the actual transcript data
    print(transcript.fetch())
 
    # translating the transcript will return another
    # transcript object
    print(transcript.translate('vi').fetch())
    # creating or overwriting a file "subtitles.txt" with 
    # the info inside the context manager
    vietnam = transcript.translate('vi').fetch()
    with open("subtitles_vn.txt", "w",encoding="utf-8") as f:
        for i,j in zip(srt,vietnam):
            # writing each element of srt on a new line
            f.write("{}\n".format(i))
            f.write("{}\n".format(j))
